### PR TITLE
fixed compilation with OCaml 4.05

### PR DESCRIPTION
**Pull request by andyli**
caused by new functions added to the standard library's Map module

### CODE REVIEW

**Comment by UnixJunkie** [comment]
@backtracking @andyli the upstream repository is https://github.com/backtracking/ptmap
please send your pull request there

**Comment by UnixJunkie** [comment]
I referenced your pull request there: https://github.com/backtracking/ptmap/issues/3

**Comment by andyli** [comment]
I thought you are the maintainer since this repo is listed in https://opam.ocaml.org/packages/ptmap/.
Would it make sense to update opam to point to https://github.com/backtracking/ptmap instead?

**Comment by UnixJunkie** [comment]
yes

**Comment by UnixJunkie** [comment]
sorry, this repo was transferred back to Jean-Christophe since he moved many of his excellent source codes to github recently.

**Comment by andyli** [comment]
No problem :)
I've just sent a PR to request the change.

**Pull request closed without merging**
